apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-postgres
  labels:
    db: profile-postgres
spec:
  selector:
    matchLabels:
      db: profile-postgres
  template:
    metadata:
      labels:
        db: profile-postgres
    spec:
      containers:
        - name: profile-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: cs_profile
#          resources:
#            requests:
#              cpu: 100m
#              memory: 60Mi
#            limits:
#              cpu: 200m
#              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: profile-postgres
  labels:
    db: profile-postgres
spec:
  type: ClusterIP
  selector:
    db: profile-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432